### PR TITLE
add fraxtal, update description, and include curve lend for Beefy

### PR DESCRIPTION
**Pull request by EPETE-EPETE**
not sure if adding fraxtal will cause and issue, I don't see it on any other integrations.

### CODE REVIEW

**Review by philippe-git — CHANGES_REQUESTED** [review]
No it won't cause issues, thanks for double-checking!

Before merging this PR, does Beefy have features that allow to mint/etc crvUSD? Simply allowing the token itself to be used in the app (like any other erc20 token) doesn't qualify for the "crvusd" tag since we want this tag to help crvusd users find out apps specifically providing tools/data/etc for crvusd itself

**Comment by EPETE-EPETE** [comment]
Beefy has vaults building on top of Curve Lend, it appears that having the crvUSD tag is what gets it to show up on the Integrations for Curve Lend.
https://app.beefy.com/vault/curve-lend-crv-crvusd as an example, also have more on Arbitrum.
image

**Comment by philippe-git** [comment]
Nice vaults! The fact that "crvusd" tags are shown on the Curve Lend site is an error, we'll have it fixed, thanks for noticing it! Could you use the "lend" tag instead please? We'll make sure this tag is what gets shown the on the Curve Lend site

**Comment by EPETE-EPETE** [comment]
appreciate the help. Should be good now!

**Pull request merged**
